### ISSUE TITLE
Error when opening 360° viewer

### ISSUE THREAD

**Issue by KT0n3** [cazitouni/QgisGLViewer#10]
After opening the 360° viewer, the following error occurs:

WARNING    Traceback (most recent call last):
File "/QGIS/QGIS3\profiles\default/python/plugins\QgisGLViewer\EquiView360.py", line 164, in mouseMoveEvent
dx = event.pos().x() - self.mouse_x
AttributeError: 'GLWidget' object has no attribute 'mouse_x'

This error keeps occuring when the mouse hovers over the image but dissapears once the user clicks on the image.

**Comment by cazitouni** [comment]
Hello @KT0n3, 

Thanks for the feedback, it seems the viewer didn't get your mouse position within the windows which is a bit strange.
Which OS/Qgis version are you using ? 

Also, if you could provide a qgis project and a sample of image I could look into it to debug it. 

Thanks again, 
Regards, Clément.

**Comment by KT0n3** [comment]
Hello Clément,

Thank you for the quick answer. I'm using Windwos 11 and Qgis 3.28.3. I've attached a project and an image so you can try to replicate the issue.

I also get the following error when closing the viewer:

IndexError: list index out of range 
Traceback (most recent call last):
File "/QGIS/QGIS3\profiles\default/python/plugins\QgisGLViewer\EquiView360.py", line 213, in apply_inertia
self.map_manager.modify_line_direction(self.direction, self.instance)
File "/QGIS/QGIS3\profiles\default/python/plugins\QgisGLViewer\Helpers.py", line 71, in modify_line_direction
line = self.rubberbands[0]
IndexError: list index out of range

Thank you,

Regards, Quentin.

[Qgis Project.zip](https://github.com/cazitouni/QgisGLViewer/files/15036920/Qgis.Project.zip)

**Comment by cazitouni** [comment]
Hello @KT0n3, 

At first, everything's fine on my Windows 10/Qgis 3.28 machine using your project. I'll try on my Windows 11 machine this weekend.
![image](https://github.com/cazitouni/QgisGLViewer/assets/92778930/d41a07e1-21d6-417d-bb9a-2fdb357ee63a)

Another thing you could try is uninstalling the plugin and using this zip version which is more up to date, I'll have modified a  few things in it already and it could maybe solve the problem. 

Thanks,
Regards, Clément.

[QgisGLViewer.zip](https://github.com/cazitouni/QgisGLViewer/files/15038406/QgisGLViewer.zip)

**Comment by KT0n3** [comment]
Thanks for the feedback,

I just updated my version of Qgis to 3.36 and the plugin version and everything works fine now. I guess the issue is solved. Thank you for your help and your awesome work on this plugin!

Regards, Quentin.
