### ISSUE TITLE
Issue with Gap value

### ISSUE THREAD

**Issue by snorimaps** [cazitouni/QgisGLViewer#3]
Hi

There seems to be an issue with Gap value calculation, Its way longer than intended (5m)...probably a CRS issue? I'm using CRS 4326.

![image](https://user-images.githubusercontent.com/22559395/224663700-eb4bcfa3-a0c0-4652-909e-18b0d7d9ce17.png)

Geopkg file:
[photos4.zip](https://github.com/cazitouni/QgisGLViewer/files/10955792/photos4.zip)

**Comment by snorimaps** [comment]
I would also like to suggest the following features to make this more usable:

1. Prev, Next buttons/arrows on the image viewer to move fwd or back through the image equence. An Image 'id' column could be used to maintain sequencing
2. Ability to use mouse to click a location/point and for the image to open in the same image window without resetting the window position, zoom and view angle. 
Currently each time we need to select a different image for viewing, we would have to click on the plugins button in toolbar, select a point which would then open a new image window

**Comment by cazitouni** [comment]
Hello @snorimaps, Thanks for using my plugin and for your feedback. 
Indeed the issue could be related to the EPSG:4326 projection. Is it possible for you to send me a sample of your images with the associated geopackages for me to test it and fix the issue ?
Otherwise ,you could try to reproject the points in 3857 it should wok as well. 

For your suggestions : 
It's possible to move within the image by clicking on it in the right direction, the gap parameter will define the "jump" distance. But I could look to add buttons based on the ID it shouldn't be very difficult. 
For the second point, It could be a little more difficult to code But I could look into it as well.

Thanks again, for your feedback and suggestions.

**Comment by snorimaps** [comment]
Hi, Thanks for your very useful plugin!

Reg, the geopkg, I've attached the file to my original post at the bottom (zip file). The images are quite big,

The issue with navigating through the image is that due to the very high jump distance, when I click on the image it directly jumps to the very last image in the sequence, or even beyond that and says no image available. Clearly the issue is the Gap distance representation on map as you can see on the map image on my original post. For scale, the images are only about 3-5m apart.

I'm also attaching the images file folder here.

https://we.tl/t-JOuheCp5sH

Thank you!

**Comment by cazitouni** [comment]
Thanks for the sharing.

I've tried several modifications, the rubberband and the jump function should be good for 4326 now, even if the precision isn't very accurate with this projection. 
I've tried with your dataset but the direction seems a bit off. But I've also tried with some of mines and everything seems to works well. 

Would you tried to install the extension with the attached zip and tell me if it works for you  ?

Thank you in advance. 

[QgisGLViewer.zip](https://github.com/cazitouni/QgisGLViewer/files/10962513/QgisGLViewer.zip)

**Comment by snorimaps** [comment]
I've tested it with the zip version, the gap distance issue seems to have been resolved, thanks.
![image](https://user-images.githubusercontent.com/22559395/224971181-0de3a5fb-3dfa-448c-9bf4-6e0ea8359854.png)


Yes the direction/azimuth attributes seems to be off, in my data.

I think previous/next image buttons or click on map options would be great enhancements. 

Thanks for your work!

**Comment by cazitouni** [comment]
Thanks you for your answer. 
I've commited the fixes to github and it will come on Qgis repo with version 1.3 in a few days. 
I will look forward to implement the buttons in a future version. 

Do not hesitate to contact me again if you have any issues, I will close this one for now. 

Kind regards, Clément.
