### ISSUE TITLE
Instructions for installing on MacOS Sonoma

### ISSUE THREAD

**Issue by tiagodts** [cazitouni/QgisGLViewer#9]
1. Close QGIS.
2. Navigate to the symbolic link to Python3 within the QGIS application at /Applications/QGIS.app/Contents/MacOS/bin/python3. This will open a Terminal window with a message about the version of Python is running and will end with the interactive prompt >>>.
3. Enter the command `import os`
4. Install the libraries needed for QgisGLViewer:

`os.system('/Applications/QGIS.app/Contents/MacOS/bin/python3 -m pip install pyOpenGL')` `os.system('/Applications/QGIS.app/Contents/MacOS/bin/python3 -m pip install pyOpenGL_accelerate')`

**Comment by cazitouni** [comment]
Thanks, I will integrate it.
